// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtmFmqjIesPq37O_wpZZED1GxLo-1Z9ZE',
    appId: '1:526759731809:web:1bab48ab3f6ee3e23ec020',
    messagingSenderId: '526759731809',
    projectId: 'todoapp-28895',
    authDomain: 'todoapp-28895.firebaseapp.com',
    storageBucket: 'todoapp-28895.appspot.com',
    measurementId: 'G-7B5Q2F3340',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8YYNrndpymNaOVPBkc2qC2_ZrxyNZDbE',
    appId: '1:526759731809:android:b0be2e24503d35633ec020',
    messagingSenderId: '526759731809',
    projectId: 'todoapp-28895',
    storageBucket: 'todoapp-28895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLik7m47jEDQq_G65arzHhjfkDwGfzTQ',
    appId: '1:526759731809:ios:764feb78942803d93ec020',
    messagingSenderId: '526759731809',
    projectId: 'todoapp-28895',
    storageBucket: 'todoapp-28895.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLik7m47jEDQq_G65arzHhjfkDwGfzTQ',
    appId: '1:526759731809:ios:764feb78942803d93ec020',
    messagingSenderId: '526759731809',
    projectId: 'todoapp-28895',
    storageBucket: 'todoapp-28895.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtmFmqjIesPq37O_wpZZED1GxLo-1Z9ZE',
    appId: '1:526759731809:web:356afd1663dc67f33ec020',
    messagingSenderId: '526759731809',
    projectId: 'todoapp-28895',
    authDomain: 'todoapp-28895.firebaseapp.com',
    storageBucket: 'todoapp-28895.appspot.com',
    measurementId: 'G-CX1E0GTZLV',
  );
}